POST https://cna-email-service.azurewebsites.net/process-order
Authorization: Bearer token

{
  "orderData": {
    "products": [
      {
        "name": "Product 1",
        "quantity": 2
      },
      {
        "name": "Product 2",
        "quantity": 1
      }
    ]
  }
}

###

POST https://cna-user-api.duckdns.org/register
Content-Type: application/json

{
    "username": "token",
    "password": "token",
    "email": "token@arcada.fi"
}

###
POST https://cna-user-api.duckdns.org/login
Content-Type: application/json

{
    "username": "token",
    "password": "token"
}